### ISSUE TITLE
startx on tty1 and slim on tty7

### ISSUE THREAD

**Issue by pepa65** [fsmithred/refractasnapshot-base#3]
The snapshot-iso has startx on tty1 and slim on tty7 due to how live-config works.
I would propose to add the line `touch "$work_dir"/myfs/etc/profile.d/zz-live-config_xinit.sh` at an appropriate place in `refractasnapshot` so we only have slim operating and not and extra desktop on tty1 as well. (See `/lib/live/config/0140-xinit`.)

**Comment by fsmithred** [comment]
I think that would break it for those who want autologin without a display
manager. 0140-xinit should exit if slim was configured (in 0130-slim). Is
something broken in the slim config? I'm just seeing a tty on tty1 in the
devuan desktop-live iso.

Can you try adding 'nocomponents=xinit' to the boot command to see if that
fixes it?

**Comment by pepa65** [comment]
When adding `nocomponents=xinit`there is no desktop on tty1 in the live session.

To clarify, this is making a snapshot from a Devuan install (installed from the Devuan live CD). I am trying to get a reasonable install from the snapshot.

**Comment by fsmithred** [comment]
I installed devuan from the desktop-live. I made a snapshot, imaged a usb
stick and booted into the live session. It logs into xfce automatically as
it should.

ctrl-alt-F1 brings me to tty1, where user is already logged in as expected.
ctrl-alt-F7 brings me back to the desktop.

I am unable to reproduce your problem (or I don't understand what the
problem is.) We should take this conversation somewhere else. Please post
at dev1galaxy.org or file a bug report against the package at
bugs.devuan.org so we can get more eyes on this problem.

**Comment by pepa65** [comment]
I installed MATE, perhaps that caused a difference. My goal is not to produce am installable image for general use, but for a select audience, and I want it to be properly locked down, so I guess my goals are different than the general live user.

Anyway, the live package is versatile, and I can make it work. Not sure why I had 2 desktop sessions happening.
